### PR TITLE
included txt reading option for blind + med, b cat flexibility

### PR DESCRIPTION
**Pull request by dpinna**

### CODE REVIEW

**Comment by zucchett** [comment]
Hi Deborah,
there is probably a better solution than adding +1 to the index if we are running blind: if combine does not provide the obs, can we just make it add one default value?
In my opinion, playing with indices always cause problems sooner or later.
This is a suggestion, if you already thought about this i'll merge the PR.

**Comment by dpinna** [comment]
Hi Alberto,

there might indeed be a better solution. The problem is that, as I understood, in the file saved from combine the label obs or exp is lost. Only the numbers are saved. The problem is then, that when obs is not in the list there is one line less but the limit.py still starts reading from the first line and associated to obs and so on.. So what is plotted does is messed up. Any other suggestions on how to change this?

**Comment by dpinna** [comment]
Hi Alberto, 
I would have to think how to make this in combine. I am not sure if that would make things "safer". I can think a bit more about it and check if I can find a solution as you suggest.

**Comment by dpinna** [comment]
Hi Albe, I have updated the pull request, could you check if now it's ok?
In the end, in the blind=true case I have included a "0" as first line in the txt file because and simple "empty line" was causing problems in the limit plotting

**Pull request merged**
