### PR TITLE
add missing info to reconstruct 4-vect + fixes to dphi vars

### PR DESCRIPTION
**Pull request by dpinna**

### CODE REVIEW

**Comment by zucchett** [comment]
Hi Deborah, a couple of questions for my education:
1) why setting up the Jet1, Jet2, ... TLorentzVectors in the code has been commented (e.g.  line 1263)? Don't we use them anywhere else?
2) Do we need the lepton energy? (the mass of the electron and muon is known and fixed, unlike jets)
3) Do we want 6 jets now?....is there a special need for that?

**Comment by dpinna** [comment]
Hi Alberto,

1. I have checked and they are not used anywhere. I was also surprised.. I have also tested the code locally and everything seems fine.

2. True, but I thought that it was more convenient to have the full information all together in the tree. I can remove this part if you prefer.

3. I thought that if we want to build variables without going back to SFrame 6 jets might be better for the hadronic case. 4 jets is the minimum expected for the single top. I can lower it back if preferred.

**Comment by zucchett** [comment]
1. Ok, we can leave it as is...
2. Yes, the mass is simply 105 MeV for the muon and 511 keV for the electron, so we can always reconstruct the 4-momentum even afterwards
3. Ok, 6 jets looks a lot to me, but if this is temporary we can leave them.
It's unrelated to this PR, but a current production is 60 GB now, wayy more than what i expected

**Comment by clseitz** [comment]
Did you guys decide on this PR?

**Comment by zucchett** [comment]
I thought we decided to remove the lepton energy (which is redundant), and add the 6 jets (temporarily!).  But if this is too much work and you need it tonight, i can merge it.

**Comment by dpinna** [comment]
this is my fault guys..I promised to change the electron and muon part and do another commit. It is just that I made some changes for the sync exercise and I have to remove that part as well before doing the commit. I will do it at the latest tomorrow morning so that you can accept the pull request

**Comment by dpinna** [comment]
Could you check if the pull request is updated? I have commented out the sync part and the E info for the leptons. Thanks!

**Pull request merged**
